name: OnlyPull CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  job1:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Git Pull
        run: |
          cd "C:/Users/mts/Documents/test_jenkins"
          date > generated.txt
          git pull
      # - name: git pull
      #   shell: pwsh
      #   run: |
      #      cd C:/Users/mts/Documents/test_jenkins
      #      git pull
      - name: IIS restart
        shell: pwsh
        run: |
          iisreset 
